### ISSUE TITLE
Privacy Policy & Terms and Conditions

### ISSUE THREAD

**Issue by jadasi** [OverstepCo/fun-sports-pools-app#10]
We will eventually need these. Preferably in a PDF format (easy to convert to html).

**Comment by reddlegend** [comment]
Files are on the Docs tab on Airtable

**Comment by jadasi** [comment]
There seems to be an unfilled field. What should go in there?
![image](https://user-images.githubusercontent.com/21181131/72114629-72123080-3301-11ea-96af-d86240ce59e3.png)
