### ISSUE TITLE
Leaderboards 

### ISSUE THREAD

**Issue by AreYouAHacker** [OverstepCo/fun-sports-pools-app#14]
Add Leaderboards

**Comment by AreYouAHacker** [comment]
![image](https://user-images.githubusercontent.com/32847394/72478960-5a7af200-37b0-11ea-85e9-a93f2266fbec.png)
Should this be a general number rather than a x out of somthing?

**Comment by AreYouAHacker** [comment]
I was just trying to figure out how to grade numeric question

**Comment by jadasi** [comment]
From what I remember talking with Caleb about, a numeric question has to be an exact guess to be correct. Everything else would be wrong so it will be graded like every other question. It might be a better idea to use a point system, but that decision isn't up to me. What do you have to say @reddlegend ?

**Comment by reddlegend** [comment]
Grading is done by the absolute distance between the guess and the answer.

**Comment by jadasi** [comment]
So the winner of a pool is the person with the most points? Are multiple choice questions worth the same amount of points or can the admin define the amount of points for each question?

**Comment by reddlegend** [comment]
The winner is the person with the most points from the multiple choice questions. If there's a tie for first place (and only if there's a tie), the winner is determined by who answered the first tiebreaker best. If there's a tie there, the winner is determined by who answered the second tiebreaker best (and so on). If there's a tie after all questions have been checked, there's a tie I guess lol

**Comment by AreYouAHacker** [comment]
Okay so should MC questions all be worth the same then?

**Comment by reddlegend** [comment]
Indeed.

**Comment by jadasi** [comment]
**NEW THINGS THAT NEED TO BE DONE:**
- When a pool is active, scoring is out of 12. Should be out of 10. Don't count the numeric questions.
- Currently David and I are tied at a whopping 3/12 correct (woo!). I should win because my first tiebreaker answer is closest. When I set the pool to Active or Closed the app doesn't show who won based on the tiebreaker. Once all questions have been answered on the admin panel (regardless of what stage the pool is in), show an "In the Lead" badge or star or something in the leaderboard on the user who has the highest score (taking into account the tiebreaker questions if necessary).

**Comment by AreYouAHacker** [comment]
So I'm confused. Should numeric questions only be tie breakers?

**Comment by reddlegend** [comment]
@AreYouAHacker Correct. Numeric questions are only taken into account if there's a tie.

**Comment by AreYouAHacker** [comment]
Ok I see. Would it be beneficial to maybe add them to a separate section in the admin panel and app?  
![image](https://user-images.githubusercontent.com/32847394/73479150-a56e3b00-4354-11ea-91ce-cd9d54571378.png)

**Comment by reddlegend** [comment]
That would be beneficial; low priority though. For now Tim won't add them in any order except multiple choice and then numeric, so no immediate need to separate them.

**Comment by AreYouAHacker** [comment]
![image](https://user-images.githubusercontent.com/32847394/73565479-db77f180-441e-11ea-8b89-771903bce4cc.png)
The sort algorithm now takes into account the tie winners.
