### ISSUE TITLE
Adding Friends

### ISSUE THREAD

**Issue by jadasi** [OverstepCo/fun-sports-pools-app#16]
Do you need to confirm friendships or can users add anyone as their friend?

**Comment by reddlegend** [comment]
Makes sense to me to have them confirmed. Could that be something where friend requests show up on the homepage if there are any?

**Comment by jadasi** [comment]
@MadHodrick most of this issue has been fixed besides a few server-side scripts. Search `TODO` in user.js for where and what needs to be implemented.
