### ISSUE TITLE
In App Purchases

### ISSUE THREAD

**Issue by jadasi** [OverstepCo/fun-sports-pools-app#18]
I found a great plugin for cordova that supports native IAP found [here](https://github.com/j3k0/cordova-plugin-purchase).  Here is a list of cool stuff it supports:

![image](https://user-images.githubusercontent.com/21181131/72364842-6d100100-36b4-11ea-9ee8-5b20383de5e9.png)

If we used this plugin we probably wouldn't need to use Payroc. Although Payroc would probably be easier for us to implement, it's less ideal for the end user because they would have to setup a payment method while native IAPs would already have that info, support fingerprint auth, etc. I'm not for sure, but Google and Apple may have restrictions for external purchases. I would highly suggest we try to use this plugin first, or is using Payroc a non-negotiable?

**Comment by reddlegend** [comment]
Great info.
Payroc is not (pay)locked in yet. This plugin looks like a good option; we may still need to integrate Payroc with that (for actually processing the payments - there are several steps in the payment process). It would be great if you could join the call tomorrow; I'll push it to 10:15 and we can discuss all of this with Payroc's development guy.

**Comment by reddlegend** [comment]
The biggest question for the call tomorrow is probably whether we can externally process payments with Payroc or whether we have to process them through Google/Apple. If Google and Apple lock out external processors, we'll be doing 100% with this plugin.

**Comment by jadasi** [comment]
@reddlegend Is going ad-free a one time purchase or a reoccurring payment?

**Comment by reddlegend** [comment]
One time purchase
