### ISSUE TITLE
Load pool page function

### ISSUE THREAD

**Issue by AreYouAHacker** [OverstepCo/fun-sports-pools-app#20]
If we could add a function called loadPoolPage(poolID) or something then we could just call that  function whenever we need to load a pool and it would check the state of the pool then decide   how to display it

**Comment by jadasi** [comment]
I added this. You just need to use a link to /pool/ with an id parameter.
e.g. `<a href="/pool/?id=s9f798fLOQ83ms0Gk"></a>`
