### ISSUE TITLE
Async Functions Messing up Order

### ISSUE THREAD

**Issue by jadasi** [OverstepCo/fun-sports-pools-app#24]
Whenever we need ordered content (e.g. leaderboards, pools, etc.) we use asynchronous methods to get the data **then** we load the data onto the page. This defeats the whole purpose of ordered content because loading times vary. What I'm thinking we'll have to do is chain them together via callbacks somehow. Here's pseudo code of a possible recursive solution.

```javascript
var dataIDS = [sadf09asdf, d02ndbwd9d, N20ndg9cSNd0, q1n0DMs7d9m];

displayData(dataIDS);

function displayData(ids) {
    getData(ids.pop(), function(data) {
        page.append(data);
        if (ids.length > 0)
            displayData(ids);
    });
}
```

**Comment by AreYouAHacker** [comment]
Yeah, I've actually dealt with this problem before and if you use callback as you stated then it makes the async method almost as long as the default method. I can fix any methods that need to be ordered. You basically have to load have an array of callbacks that then once all data is loaded call the callbacks in order. I'll fix some of the async methods we have then you can look at the code.

**Comment by jadasi** [comment]
Sounds good. Here are the lists that need to be ordered:

- Your pools (by date)
- Pools search (by priority)
- Previous pools (by date)
- Users search (by priority)
- leaderboard (by score)
