### ISSUE TITLE
Update Answer Pool Questions Page

### ISSUE THREAD

**Issue by jadasi** [OverstepCo/fun-sports-pools-app#27]
- When answering questions, turn the whole question button green when selected rather than adding the green check mark.
- Add arrows that allow pressing to go between questions (forwards and backwards). Tim kept trying to press, wasn't intuitive for him to swipe.
- After you have answered all questions, add a button at the bottom of each question page to allow submission of new answers. People will want to go back and change their answers before the game starts; it's cumbersome to go to the last question every time you want to submit new answers.

**Comment by jadasi** [comment]
@reddlegend making these changes will require a complete refactoring of the questions page. While we are at it, can we change the look to something closer to the results page? It is a lot better use of space and more intuitive (like an actual quiz). It will also make the results page more familiar and thus easier to read.

**Comment by reddlegend** [comment]
Go ahead and make all of the changes you suggested. Good call on changing the look. **If this will push the timeframe back, save it until after other critical pieces have been done.**
