### ISSUE TITLE
Change User Profile Page

### ISSUE THREAD

**Issue by jadasi** [OverstepCo/fun-sports-pools-app#29]
On the User Profile page hide everything except the profile, friends, and previous pools. Also hide the bio section.

**Comment by jadasi** [comment]
@reddlegend So remove favorite teams & sports? Are we removing this feature from the app?

**Comment by reddlegend** [comment]
Not removing it from the app; he just wanted it hidden for Alpha. He doesn't have a complete list of teams to populate, and may change the sports available on the app before final release.
