### ISSUE TITLE
the welcome.html is not finished 

### ISSUE THREAD

**Issue by AreYouAHacker** [OverstepCo/fun-sports-pools-app#3]
![image](https://user-images.githubusercontent.com/32847394/71549414-1a2b0f80-297a-11ea-8515-f16d0944095b.png)

**Comment by jadasi** [comment]
I finished most of it. You just need to add friends from Facebook.
![image](https://user-images.githubusercontent.com/21181131/72008434-09e42180-3211-11ea-9606-0dba98ec74fe.png)

**Comment by jadasi** [comment]
**NEW THINGS THAT NEED TO BE DONE:**

-  When logging in for the first time, skip the first screen (with "Favorite Sports" and "Favorite Teams"). Go straight to the screen where you enter your name.
- Hide the bio section in the welcome screen (and remove the requirement for a bio).
