### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by jadasi** [OverstepCo/fun-sports-pools-app#35]
![image](https://user-images.githubusercontent.com/21181131/73797604-c4face80-476d-11ea-9236-13fe307f5c17.png)

**Comment by jadasi** [comment]
@reddlegend where would you like to place ads? Before answering questions, before submitting answers, before viewing results? should a banner ad always be showing? 

There are two types of ads: banner and interstitial. click [here](https://github.com/floatinghotpot/cordova-admob-pro#screenshots) to view what they look like. 

**Note:** interstitial ads give 10 times more revenue than banner ads.

**Comment by reddlegend** [comment]
How's this:
 - Show a banner ad everywhere except when answering questions
 - Show an interstitial ad immediately when you go to answer the questions (until they have all been answered)
 - Show an interstitial ad one out of every five times when you view results (opening the pool once the game is Closed - Game in Progress)

Can that be done?
