### ISSUE TITLE
Home Screen Reload

### ISSUE THREAD

**Issue by jadasi** [OverstepCo/fun-sports-pools-app#9]
When you go two pages in and then back home it doesn't load.

**Comment by AreYouAHacker** [comment]
Hmm.. could you provide an example I can't seem to replicate it?

**Comment by jadasi** [comment]
Click: user profile > edit user > back > back

**Comment by AreYouAHacker** [comment]
So I fixed this for the specified case however it is still possible it may happen. In the future, if you want to navigate to the main page you should always call loadMainPage() and this solves the issue. If for some reason we need to navigate to the main page in a different way I can revisit this solution.

**Comment by AreYouAHacker** [comment]
I going to leave this open in case it is still broken somewhere

**Comment by AreYouAHacker** [comment]
ok i found a better fix for this
